version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db

  backend:
    build: backend
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - postgres
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - POSTGRES_URI=postgresql://admin:password@postgres:5432/users_db

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: "http://backend:3000"

volumes:
  postgres_data:
  mongo_data: